name: irwin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    # syncfusion_flutter_datepicker: ^19.1.57-beta
    # custom_radio_grouped_button: any
  # sidenavbar: ^0.0.2
  # get:
  # custom_switch: ^0.0.1
  flutter_switch: ^0.3.2
  # dropdown_button2:
  # list_tile_switch: ^1.0.0
  custom_radio_grouped_button: any
  bubble_bottom_bar: ^2.0.0
  pinput: 1.1.0
  timer_count_down:
  sizer: ^2.0.15
  # json_table: ^2.0.1
  data_table_2: ^2.3.6
  flutter_speed_dial: ^6.0.0
  google_fonts: ^2.3.1 #fonts
  intl: ^0.17.0
  date_format: ^2.0.6
  # flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.1.5
  file_picker: ^4.1.3
  dio: ^4.0.6
  path_provider: ^2.0.5
  open_file: ^3.2.1
   
  # share_plus: ^3.0.5
  # file_picker: ^1.9.0+1
  

  # sidebar: ^0.3.1
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  syncfusion_flutter_datepicker: ^19.1.57-beta
  list_tile_switch: ^1.0.0
  get:
  http:
  fluttertoast:
  shared_preferences: ^2.0.15
  # another_flushbar: ^1.10.28
  # custom_switch: ^0.0.1
  # json_table: ^2.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    # syncfusion_flutter_datepicker: ^19.1.57-beta

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mobilelogin.png
    - assets/mobilelogin.png
    - assets/person.png
    - assets/fill.png
    # - assets/ProfileImage.jpg
    - assets/arrowback.png
    - assets/Group 7.png
    - assets/login.png
    - assets/search.png
    - assets/filter.png
    - assets/pdf.png
    - assets/Group 18.png
    - assets/draft.png
    - assets/call.png
    - assets/home.png
    - assets/list.png
    - assets/info.png
    - assets/lock.png
    - assets/gavel.png
    - assets/verified.png
    - assets/logout.png
    - assets/calendar.png
    - assets/ChangePassword.png
    
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
